import type { Theme, ThemeConfig } from "@/components/notes/types";

export const themes: Record<Theme, ThemeConfig> = {
  default: {
    name: "Default",
    primary: "from-indigo-500 to-purple-600",
    primaryHover: "from-indigo-600 to-purple-700",
    accent: "indigo",
    background: "bg-white",
    text: "text-black",
    border: "border-gray-200",
    hover: "hover:border-indigo-300",
    pill: "hover:from-indigo-50 hover:to-purple-50 hover:border-indigo-300",
    iconColor: "text-indigo-600",
  },
  nature: {
    name: "Nature",
    primary: "from-emerald-500 to-teal-600",
    primaryHover: "from-emerald-600 to-teal-700",
    accent: "emerald",
    background: "bg-white",
    text: "text-black",
    border: "border-gray-200",
    hover: "hover:border-emerald-300",
    pill: "hover:from-emerald-50 hover:to-teal-50 hover:border-emerald-300",
    iconColor: "text-emerald-600",
  },
  sunset: {
    name: "Sunset",
    primary: "from-orange-500 to-red-500",
    primaryHover: "from-orange-600 to-red-600",
    accent: "orange",
    background: "bg-white",
    text: "text-black",
    border: "border-gray-200",
    hover: "hover:border-orange-300",
    pill: "hover:from-orange-50 hover:to-red-50 hover:border-orange-300",
    iconColor: "text-orange-600",
  },
  midnight: {
    name: "Midnight",
    primary: "from-cyan-400 to-blue-500",
    primaryHover: "from-cyan-500 to-blue-600",
    accent: "cyan",
    background: "bg-slate-900",
    text: "text-white",
    border: "border-slate-700",
    hover: "hover:border-cyan-400",
    pill: "hover:from-cyan-950 hover:to-blue-950 hover:border-cyan-400",
    iconColor: "text-cyan-400",
  },
  ocean: {
    name: "Ocean",
    primary: "from-blue-500 to-teal-500",
    primaryHover: "from-blue-600 to-teal-600",
    accent: "blue",
    background: "bg-white",
    text: "text-black",
    border: "border-gray-200",
    hover: "hover:border-blue-300",
    pill: "hover:from-blue-50 hover:to-teal-50 hover:border-blue-300",
    iconColor: "text-blue-600",
  },
  rose: {
    name: "Rose",
    primary: "from-pink-500 to-rose-500",
    primaryHover: "from-pink-600 to-rose-600",
    accent: "pink",
    background: "bg-white",
    text: "text-black",
    border: "border-gray-200",
    hover: "hover:border-pink-300",
    pill: "hover:from-pink-50 hover:to-rose-50 hover:border-pink-300",
    iconColor: "text-pink-600",
  },
  forest: {
    name: "Forest",
    primary: "from-green-500 to-lime-500",
    primaryHover: "from-green-600 to-lime-600",
    accent: "green",
    background: "bg-white",
    text: "text-black",
    border: "border-gray-200",
    hover: "hover:border-green-300",
    pill: "hover:from-green-50 hover:to-lime-50 hover:border-green-300",
    iconColor: "text-green-600",
  },
  galaxy: {
    name: "Galaxy",
    primary: "from-purple-400 to-pink-400",
    primaryHover: "from-purple-500 to-pink-500",
    accent: "purple",
    background: "bg-gray-900",
    text: "text-white",
    border: "border-gray-700",
    hover: "hover:border-purple-400",
    pill: "hover:from-purple-950 hover:to-pink-950 hover:border-purple-400",
    iconColor: "text-purple-400",
  },
  azure: {
    name: "Azure",
    primary: "from-blue-500 to-blue-700",
    primaryHover: "from-blue-600 to-blue-800",
    accent: "blue",
    background: "bg-white",
    text: "text-black",
    border: "border-blue-200",
    hover: "hover:border-blue-400",
    pill: "hover:from-blue-50 hover:to-blue-50 hover:border-blue-400",
    iconColor: "text-blue-600",
  },
  emerald: {
    name: "Emerald",
    primary: "from-green-500 to-green-700",
    primaryHover: "from-green-600 to-green-800",
    accent: "green",
    background: "bg-white",
    text: "text-black",
    border: "border-green-200",
    hover: "hover:border-green-400",
    pill: "hover:from-green-50 hover:to-green-50 hover:border-green-400",
    iconColor: "text-green-600",
  },
  coral: {
    name: "Coral",
    primary: "from-orange-500 to-pink-500",
    primaryHover: "from-orange-600 to-pink-600",
    accent: "orange",
    background: "bg-gradient-to-br from-orange-50 via-pink-50 to-purple-50",
    text: "text-gray-800",
    border: "border-orange-200",
    hover: "hover:border-orange-400",
    pill: "hover:from-orange-50 hover:to-pink-50 hover:border-orange-400",
    iconColor: "text-orange-600",
  },
  arctic: {
    name: "Arctic",
    primary: "from-slate-400 to-blue-300",
    primaryHover: "from-slate-500 to-blue-400",
    accent: "slate",
    background: "bg-gradient-to-br from-slate-50 via-blue-50 to-white",
    text: "text-slate-800",
    border: "border-slate-300",
    hover: "hover:border-slate-400",
    pill: "hover:from-slate-50 hover:to-blue-50 hover:border-slate-400",
    iconColor: "text-slate-600",
  },
  volcano: {
    name: "Volcano",
    primary: "from-red-600 to-yellow-500",
    primaryHover: "from-red-700 to-yellow-600",
    accent: "red",
    background: "bg-gradient-to-br from-red-50 via-orange-50 to-yellow-50",
    text: "text-red-900",
    border: "border-red-300",
    hover: "hover:border-red-400",
    pill: "hover:from-red-50 hover:to-yellow-50 hover:border-red-400",
    iconColor: "text-red-600",
  },
  neon: {
    name: "Neon",
    primary: "from-lime-400 to-cyan-400",
    primaryHover: "from-lime-500 to-cyan-500",
    accent: "lime",
    background: "bg-black",
    text: "text-lime-400",
    border: "border-lime-500",
    hover: "hover:border-lime-400",
    pill: "hover:from-lime-950 hover:to-cyan-950 hover:border-lime-400",
    iconColor: "text-lime-400",
  },
  holographic: {
    name: "Holographic",
    primary: "from-purple-500 via-pink-500 via-blue-500 to-cyan-500",
    primaryHover: "from-purple-600 via-pink-600 via-blue-600 to-cyan-600",
    accent: "purple",
    background: "bg-gradient-to-br from-purple-900 via-blue-900 to-black",
    text: "text-white",
    border: "border-purple-400",
    hover: "hover:border-pink-400",
    pill: "hover:from-purple-900 hover:to-blue-900 hover:border-purple-400",
    iconColor: "text-purple-400",
  },
  vintage: {
    name: "Vintage",
    primary: "from-amber-600 to-orange-700",
    primaryHover: "from-amber-700 to-orange-800",
    accent: "amber",
    background: "bg-gradient-to-br from-amber-50 via-orange-50 to-yellow-50",
    text: "text-amber-900",
    border: "border-amber-300",
    hover: "hover:border-amber-400",
    pill: "hover:from-amber-100 hover:to-orange-100 hover:border-amber-400",
    iconColor: "text-amber-700",
  },
};